//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mediaplayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mediaplayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animacije.
        /// </summary>
        public static string Animacije {
            get {
                return ResourceManager.GetString("Animacije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avtor.
        /// </summary>
        public static string Avtor {
            get {
                return ResourceManager.GetString("Avtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka.
        /// </summary>
        public static string Datoteka {
            get {
                return ResourceManager.GetString("Datoteka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Dodaj {
            get {
                return ResourceManager.GetString("Dodaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj žanr.
        /// </summary>
        public static string Dodaj_žanr {
            get {
                return ResourceManager.GetString("Dodaj žanr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izhod.
        /// </summary>
        public static string Izhod {
            get {
                return ResourceManager.GetString("Izhod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastnosti.
        /// </summary>
        public static string Lastnosti {
            get {
                return ResourceManager.GetString("Lastnosti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naloži.
        /// </summary>
        public static string Naloži {
            get {
                return ResourceManager.GetString("Naloži", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov.
        /// </summary>
        public static string Naslov {
            get {
                return ResourceManager.GetString("Naslov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavitve.
        /// </summary>
        public static string Nastavitve {
            get {
                return ResourceManager.GetString("Nastavitve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odstrani.
        /// </summary>
        public static string Odstrani {
            get {
                return ResourceManager.GetString("Odstrani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orodja.
        /// </summary>
        public static string Orodja {
            get {
                return ResourceManager.GetString("Orodja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostalo.
        /// </summary>
        public static string Ostalo {
            get {
                return ResourceManager.GetString("Ostalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seznam.
        /// </summary>
        public static string Seznam {
            get {
                return ResourceManager.GetString("Seznam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrani.
        /// </summary>
        public static string Shrani {
            get {
                return ResourceManager.GetString("Shrani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika.
        /// </summary>
        public static string Slika {
            get {
                return ResourceManager.GetString("Slika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremeni jezik.
        /// </summary>
        public static string Spremeni_jezik {
            get {
                return ResourceManager.GetString("Spremeni jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uredi.
        /// </summary>
        public static string Uredi {
            get {
                return ResourceManager.GetString("Uredi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V redu.
        /// </summary>
        public static string V_redu {
            get {
                return ResourceManager.GetString("V redu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žanr.
        /// </summary>
        public static string Žanr {
            get {
                return ResourceManager.GetString("Žanr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapri.
        /// </summary>
        public static string Zapri {
            get {
                return ResourceManager.GetString("Zapri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvrst.
        /// </summary>
        public static string Zvrst {
            get {
                return ResourceManager.GetString("Zvrst", resourceCulture);
            }
        }
    }
}
